# .github/workflows/docker-image.yml
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    # Use self-hosted runner with specific labels
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build Docker image
        run: docker build -t simple-node-app .

      - name: Run Docker container
        run: docker run -d -p 3000:3000 simple-node-app

      - name: Wait for the server to start
        run: sleep 10

      - name: Test application
        run: curl http://localhost:3000/